import { Incubatee, Event, Club, TeamMember, Facility } from './types';

export const incubatees: Incubatee[] = [
  {
    id: 1,
    slug: 'dostbin',
    name: 'Dostbin',
    logo: 'https://dostbin.com/wp-content/uploads/2024/05/20240516_170757_0000-1-100x100.png',
    tagline: 'Smart Bins for a Cleaner Planet.',
    description: 'Dostbin revolutionizes waste management with its smart, eco-friendly bins. Our bins, made from 95% biodegradable materials and equipped with IoT sensors, are designed for modern urban environments to optimize waste collection and promote sustainability.',
    industry: 'CleanTech',
    founders: [
      { name: 'Shivam Kumar', photo: 'https://picsum.photos/seed/shivam/200', background: 'Co-Founder & CEO' },
      { name: 'Garvit Singh', photo: 'https://picsum.photos/seed/garvit/200', background: 'Co-Founder & CTO' }
    ],
    foundingDate: '2023-04-15',
    stage: 'MVP',
    achievements: ['Won the "Green Innovation" challenge at BMSIT.', 'Developed a working prototype with 95% biodegradability.', 'Featured in local sustainability forums.'],
    website: 'https://dostbin.com/',
    socials: { linkedin: 'https://www.linkedin.com/company/dostbin/' },
    status: 'Current',
  },
  {
    id: 2,
    slug: 'margros',
    name: 'Margros',
    logo: 'https://margros.in/wp-content/uploads/2023/04/margros-logo.png',
    tagline: 'Restaurant Marketing, Perfected.',
    description: 'Margros is a full-stack marketing and growth platform for restaurants. We provide data-driven solutions including targeted ads, CRM, and loyalty programs to help restaurants increase their revenue and build a strong brand.',
    industry: 'MarTech',
    founders: [{ name: 'Vikram Singh', photo: 'https://picsum.photos/seed/vikramsingh/200', background: 'Founder & Growth Strategist' }],
    foundingDate: '2023-01-20',
    stage: 'Growth',
    achievements: ['Onboarded 100+ restaurants in Bangalore.', 'Increased average client revenue by 25%.', 'Launched a new analytics dashboard.'],
    website: 'https://margros.in/',
    socials: { linkedin: 'https://www.linkedin.com/company/margros/' },
    status: 'Current',
  },
  {
    id: 3,
    slug: 'woosta',
    name: 'Woosta',
    logo: 'https://www.woostaa.com/assets/img/logo.png',
    tagline: 'Find Your Happy Place.',
    description: 'Woosta offers hassle-free housing solutions for students and professionals. From finding the perfect PG or co-living space to managing rent and maintenance, Woosta simplifies urban living with a verified and secure platform.',
    industry: 'PropTech',
    founders: [{ name: 'Priya Sharma', photo: 'https://picsum.photos/seed/priyasharma/200', background: 'Founder & CEO' }],
    foundingDate: '2022-09-10',
    stage: 'Growth',
    achievements: ['Completed over 10,000 successful bookings.', 'Expanded services to three major cities.', 'Partnered with over 500 property owners.'],
    website: 'https://www.woostaa.com/',
    socials: { linkedin: '#' },
    status: 'Current',
  },
  {
    id: 4,
    slug: 'sentinel-ai',
    name: 'Sentinel AI',
    logo: 'https://picsum.photos/seed/sentinelai/200',
    tagline: 'Cybersecurity, Evolved.',
    description: 'Sentinel AI leverages machine learning to proactively detect and neutralize cyber threats before they can cause damage, providing next-gen security for the enterprise.',
    industry: 'Cybersecurity',
    founders: [{ name: 'Aria Sharma', photo: 'https://picsum.photos/seed/ariasharma/200', background: 'CISSP, ex-NSA' }],
    foundingDate: '2023-02-10',
    stage: 'Growth',
    achievements: ['Protected 5 Fortune 500 companies', 'Raised $5M Series A'],
    website: '#',
    socials: { linkedin: '#', twitter: '#' },
    status: 'Current',
  },
  {
    id: 5,
    slug: 'agri-sphere',
    name: 'AgriSphere',
    logo: 'https://picsum.photos/seed/agrisphere/200',
    tagline: 'Precision agriculture for a sustainable future.',
    description: 'AgriSphere uses drone imagery and soil sensors to provide farmers with actionable insights, optimizing crop yields and reducing environmental impact.',
    industry: 'AgriTech',
    founders: [{ name: 'Ben Carter', photo: 'https://picsum.photos/seed/bencarter/200', background: 'PhD in Agronomy' }],
    foundingDate: '2022-08-20',
    stage: 'MVP',
    achievements: ['Increased crop yield by 22% in pilot farms', 'Winner of the National AgriTech Innovation Award'],
    website: '#',
    socials: { linkedin: '#' },
    status: 'Current',
  },
  {
    id: 6,
    slug: 'fin-wise',
    name: 'FinWise',
    logo: 'https://picsum.photos/seed/finwise/200',
    tagline: 'Your personal AI financial advisor.',
    description: 'An AI-powered app that provides personalized financial planning, investment advice, and budgeting tools to help users achieve their financial goals.',
    industry: 'FinTech',
    founders: [{ name: 'Chloe Davis', photo: 'https://picsum.photos/seed/chloedavis/200', background: 'Ex-Goldman Sachs Analyst' }],
    foundingDate: '2023-01-05',
    stage: 'MVP',
    achievements: ['10,000+ beta users', 'Featured on TechCrunch Disrupt'],
    website: '#',
    socials: { linkedin: '#', twitter: '#' },
    status: 'Current',
  },
  {
    id: 7,
    slug: 'bhisma',
    name: 'Bhisma',
    logo: 'https://picsum.photos/seed/bhisma/200',
    tagline: 'Advanced drone technology for industrial applications.',
    description: 'Bhisma develops and deploys autonomous drones for industrial inspections, surveying, and security, providing high-precision data and enhancing safety.',
    industry: 'Drone Technology',
    founders: [{ name: 'Aditya Rao', photo: 'https://picsum.photos/seed/adityarao/200', background: 'Aerospace Engineer' }],
    foundingDate: '2021-12-05',
    stage: 'Growth',
    achievements: ['Secured a major contract for pipeline inspection.', 'Achieved level 4 autonomy in drone fleet.'],
    website: '#',
    socials: { linkedin: '#' },
    status: 'Alumni',
  },
];

export const events: Event[] = [
  {
    id: 1,
    slug: 'code-red-hackathon',
    name: 'Code-Red 3.0',
    tagline: 'The Ultimate 36-Hour Hackathon',
    banner: 'https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/banner/690353cd7c22f_code-red-30.png?d=1920x557',
    date: '2024-12-13',
    time: '6:00 PM onwards',
    venue: 'BMSIT Campus',
    status: 'Upcoming',
    organizer: 'IIC & Code-AI Club',
    description: 'Code-Red 3.0 is a 36-hour offline hackathon where developers, designers, and innovators unite to create solutions for real-world problems across various domains like healthcare, fintech, and sustainability. Compete for a prize pool of INR 3 Lakhs!',
    agenda: [
        {time: "Day 1", topic: "Registration & Inauguration"},
        {time: "Day 1", topic: "Hacking Begins"},
        {time: "Day 2", topic: "Mentoring Sessions"},
        {time: "Day 2", topic: "Final Pitching"},
        {time: "Day 2", topic: "Results & Valedictory"},
    ],
    speakers: [],
    isFlagship: true,
  },
  {
    id: 2,
    slug: 'anveshana-2025',
    name: 'Anveshana National Level Prototype Competition',
    tagline: 'Prototype Pitching Competition',
    banner: 'https://d8it4huxumps7.cloudfront.net/uploads/images/opportunity/banner/67b5adc3b0138_anveshana-prototype-competition.webp?d=1920x557',
    date: '2025-09-15',
    time: '9:00 AM onwards',
    venue: 'BMSIT Campus',
    status: 'Upcoming',
    organizer: 'IIC BMSIT',
    description: 'Anveshana is the flagship event of IIC BMSIT, a national-level prototype pitching competition. It provides a platform for student innovators to showcase their groundbreaking ideas and working models to a panel of esteemed judges and investors.',
    agenda: [],
    speakers: [],
    isFlagship: true,
  },
  {
    id: 3,
    slug: 'pitch-off-2024',
    name: 'Pitch-off 2024',
    tagline: 'Your Idea, Your Pitch, Your Future',
    banner: 'https://picsum.photos/seed/pitchoff/800/1200',
    date: '2024-09-20',
    time: '10:00 AM - 4:00 PM',
    venue: 'BMSIT Auditorium',
    status: 'Upcoming',
    organizer: 'IIC',
    description: 'A high-stakes pitching competition where startups and student teams present their ideas to a panel of venture capitalists and angel investors.',
    agenda: [],
    speakers: [],
  },
   {
    id: 4,
    slug: 'ai-in-practice-workshop',
    name: 'AI in Practice Workshop',
    tagline: 'From Theory to Application',
    banner: 'https://picsum.photos/seed/aiworkshop/800/1200',
    date: '2024-08-10',
    time: '2:00 PM - 5:00 PM',
    venue: 'Seminar Hall 3',
    status: 'Upcoming',
    organizer: 'AI & ML Club',
    description: 'A hands-on workshop covering the latest AI tools and how to integrate them into your projects and startups.',
    agenda: [],
    speakers: [],
  },
   {
    id: 5,
    slug: 'envision-2024',
    name: 'Envision 2024',
    tagline: 'The Annual E-Summit',
    banner: 'https://picsum.photos/seed/envision/800/1200',
    date: '2024-04-12',
    time: 'All Day',
    venue: 'BMSIT Campus',
    status: 'Past',
    organizer: 'E-Cell',
    description: 'Envision brought together student entrepreneurs, industry leaders, and investors for a day of insightful talks, panel discussions, and networking.',
    agenda: [],
    speakers: [],
  },
  {
    id: 6,
    slug: 'design-thinking-bootcamp',
    name: 'Design Thinking Bootcamp',
    tagline: 'Innovate with Empathy',
    banner: 'https://picsum.photos/seed/designthinking/800/1200',
    date: '2024-03-05',
    time: '9:00 AM - 5:00 PM',
    venue: 'BICEP Co-working Space',
    status: 'Past',
    organizer: 'BICEP',
    description: 'An intensive two-day bootcamp on the principles of design thinking, helping teams build user-centric products and services.',
    agenda: [],
    speakers: [],
  },
];

export const clubs: Club[] = [
  {
    id: 1,
    slug: 'e-cell',
    name: 'E-Cell',
    logo: 'https://picsum.photos/seed/ecell/200',
    tagline: 'Fostering the spirit of entrepreneurship.',
    description: 'The Entrepreneurship Cell (E-Cell) is a student-run body dedicated to promoting innovation and entrepreneurship within the campus.',
    memberCount: 50,
    recruitmentStatus: 'Hiring',
    category: 'Entrepreneurship',
    establishmentDate: '2015',
    leadership: [{ name: 'Student President', role: 'President', photo: 'https://picsum.photos/seed/ecellprez/200' }],
    flagshipEvent: { name: 'Anveshana', description: 'Our annual tech and entrepreneurship festival.' },
    achievements: ['Organized 20+ events in the last year', 'Incubated 5 student-led startups'],
  },
  {
    id: 2,
    slug: 'iic',
    name: 'IIC',
    logo: 'https://picsum.photos/seed/iic/200',
    tagline: 'Institution\'s Innovation Council.',
    description: 'An initiative of Ministry of Education (MoE) to systematically foster the culture of Innovation amongst all Higher Education Institutions.',
    memberCount: 80,
    recruitmentStatus: 'Not Hiring',
    category: 'Technology',
    establishmentDate: '2019',
    leadership: [{ name: 'Faculty Coordinator', role: 'President', photo: 'https://picsum.photos/seed/iicprez/200' }],
    flagshipEvent: { name: 'Code-Red', description: 'A 24-hour coding challenge focused on innovative solutions.' },
    achievements: ['Achieved 5-star rating from MoE', 'Filed 10+ patents from student projects'],
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: 1,
    name: 'Dr. Seema Singh',
    designation: 'Dean, I.E. & BICEP Director',
    photo: 'https://picsum.photos/seed/director/300',
    qualification: 'PhD, Business Administration',
    role: 'Oversees all operations and strategic direction of BICEP.',
    bio: 'An experienced academic and mentor with a passion for fostering student innovation.',
    category: 'Faculty & Leadership',
  },
  {
    id: 2,
    name: 'Prof. Shama H M',
    designation: 'Coordinator, Innovation',
    photo: 'https://picsum.photos/seed/mentor/300',
    qualification: 'M.Tech, CSE',
    role: 'Mentors incubatees and connects them with industry experts.',
    bio: 'Specializes in product development and go-to-market strategies.',
    category: 'Faculty & Leadership',
  },
  {
    id: 3,
    name: 'Himanshu Lodha',
    designation: 'President, IIC',
    photo: 'https://picsum.photos/seed/ecellprez2/300',
    qualification: 'Student, 3rd Year CSE',
    role: 'Leads the E-Cell and represents the student entrepreneurial body.',
    bio: 'Passionate about building a vibrant startup ecosystem on campus.',
    category: 'Club Representative',
  },
];

export const facilities: Facility[] = [
  {
    id: 1,
    name: 'Arohan Lab',
    type: 'Lab',
    description: 'Equipped with 3D printers, laser cutters, and other tools to bring your hardware ideas to life.',
    image: 'https://picsum.photos/seed/lab1/800/600',
    equipment: ['3D Printers', 'Laser Cutter', 'CNC Machine', 'Soldering Stations'],
    capacity: 15,
  },
  {
    id: 2,
    name: 'Co-working Space',
    type: 'Office Space',
    description: 'A vibrant and collaborative workspace for incubatees with high-speed internet, meeting rooms, and coffee.',
    image: 'https://picsum.photos/seed/cowork/800/600',
    equipment: ['High-speed WiFi', 'Projectors', 'Whiteboards'],
    capacity: 50,
  },
  {
    id: 3,
    name: 'Ideation Room',
    type: 'Meeting Room',
    description: 'A dedicated space for brainstorming and strategy sessions, equipped with all necessary presentation tools.',
    image: 'https://picsum.photos/seed/meeting/800/600',
    equipment: ['Smart TV', 'Conference Call System', 'Whiteboards'],
    capacity: 10,
  },
];
